### ISSUE TITLE
On failure

### ISSUE THREAD

**Issue by badboycxcc** [plackyhacker/SuspendedThreadInjection#1]
![image](https://user-images.githubusercontent.com/72059221/137099663-4fc6ee50-cbbd-4372-b298-6ba5ec80c845.png)

[+] Sleeping whilst Defender scans the remote process.
Directly out of.

msf not found

**Comment by plackyhacker** [comment]
Hi, I’m not sure what the issue is. Could you describe it please? Thanks.

**Comment by plackyhacker** [comment]
It is not clear what the issue is.
